1) Create a vector of size 15 having third element (i.e. position 2) set to 1 and rest of the elements should be zero. 


In [1]:
import numpy as np

In [60]:
x = np.zeros((15))
x[2] = 1
print(x)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Create a vector with values ranging from 21 to 30


In [19]:
range = np.arange(21,31)
print(range)

[21 22 23 24 25 26 27 28 29 30]


3) Reverse the order of elements in the vector in question 2. That is, the previous last element should be the first one
now

In [20]:
range[::-1]

array([30, 29, 28, 27, 26, 25, 24, 23, 22, 21])

4) Define a vector with values ranging from 1 to 12. Now define a 4x3 matrix to store elements from the vector you have
defined. That is, first 3 elements of the vector should be row 1 of the matrix, next 3 should be row 2, and so on. 


In [75]:
v= np.arange(1,13)
vector=v.reshape(4,3)
print(vector)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


5) Consider the 4x3 matrix from question 4. Add 100 to all values that are greater than equal to 3 and less than equal to
8.

In [80]:
vector[(vector>2) & (vector<9)] += 100
print(vector)

[[  1   2 103]
 [104 105 106]
 [107 108   9]
 [ 10  11  12]]


6) Consider the vector x = [1, 0, 6, 9, 10, 0]. Print the indices of non-zero elements. 

In [6]:
x = np.array([1,0,6,9,10,0])
np.nonzero(x)

(array([0, 2, 3, 4], dtype=int64),)

7) Define a 6x3 matrix with random values. Normalize this matrix by subtracting the mean (of the column) and dividing
by the standard deviation (of the column). 

In [3]:
x = np.random.randn(18)
matrix = x.reshape(6,3)
mean = np.mean(matrix,axis=0)
sd = np.std(matrix,axis=0)
print((matrix - mean) / sd )

[[-1.99082874  0.30636632 -0.11280312]
 [ 0.2791925  -1.71145329 -0.56295073]
 [ 0.87738151 -0.21088967  2.07913468]
 [ 0.40942204  1.02815554 -0.92672362]
 [-0.46985425 -0.62878177  0.19476675]
 [ 0.89468695  1.21660287 -0.67142397]]


8) Define a 3x4 matrix with random values. Define a 4x3 matrix with random values. Multiply the two matrices. 

In [2]:
x = np.random.randn(12)
mat = x.reshape(3,4)
y = np.random.randn(12)
sec = y.reshape(4,3)
res = np.dot(mat,sec)
print(res)

[[ 6.14373528 -0.01919256  1.05970088]
 [-1.45799918  1.0259662  -0.63211155]
 [ 2.05846946  1.22407192 -0.16305257]]


9) Define a 3x3 identity matrix.

In [8]:
identity = np.eye(3,3)
print(identity)
## Identity matrix has diagnal values as 1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


10) Define a 3x3 matrix A with random values. Invert the matrix A, let’s call this B. Multiply matrices A and B

In [84]:
random = np.random.randn(9)
shape = random.reshape(3,3)
eye = np.eye(3,3)
y = eye / shape
print(shape * eye)

[[ 0.26394047 -0.          0.        ]
 [-0.         -1.38184706  0.        ]
 [-0.          0.         -1.22096911]]
