In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
dataset=pd.read_csv('data.csv')
x= dataset.iloc[:,:-1].values
y= dataset.iloc[:,4].values
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:,0] = labelencoder_x.fit_transform(x[:,0])
onehotencoder = OneHotEncoder(categorical_features=[0])
x= onehotencoder.fit_transform(x).toarray()
#x=x[:,1:]
print(x)
#from sklearn.model_selection import train_test_split
#x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

[[0. 1. 0. ... 0. 0. 2.]
 [0. 0. 1. ... 0. 0. 6.]
 [0. 0. 1. ... 0. 1. 2.]
 ...
 [0. 0. 1. ... 0. 1. 1.]
 [0. 0. 1. ... 0. 1. 1.]
 [0. 0. 1. ... 0. 1. 3.]]


C:\Users\sahithi katuri\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\sahithi katuri\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [4]:
x
print(x.shape)

(30, 5)


In [10]:
from sklearn.linear_model import LinearRegression
mlrObj=LinearRegression()
mlrObj.fit(x_train,y_train)
y_pred = mlrObj.predict(x_test)


In [11]:
y_test

array([ 37731, 122391,  57081,  63218, 116969, 109431], dtype=int64)

In [12]:
y_pred

array([ 43891.26902659, 126961.49881403,  62010.5455212 ,  61270.23196485,
       112780.99305321, 106171.56595799])

In [20]:
import statsmodels.api as sm

C:\Users\sahithi katuri\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:23: FutureWarning: The Panel class is removed from pandas. Accessing it from the top-level namespace will also be removed in the next version
  data_klasses = (pandas.Series, pandas.DataFrame, pandas.Panel)


In [32]:
x = np.append(arr=np.ones((30,1)).astype(int),values=x,axis=1)
x_sig=x[:,[0,1,2,3,4,5]]
obj_OLS = sm.OLS(endog = y, exog = x_sig).fit()
obj_OLS.summary()
x_sig=x[:,[0,1,3,4,5]]
obj_OLS = sm.OLS(endog = y, exog = x_sig).fit()
obj_OLS.summary()
x_sig=x[:,[0,1,3,5]]
obj_OLS = sm.OLS(endog = y, exog = x_sig).fit()
obj_OLS.summary()
x_sig = x[:,[0,3,5]]
obj_OLS = sm.OLS(endog = y, exog = x_sig).fit()
obj_OLS.summary()

x_sig = x[:,[0,5]]
obj_OLS = sm.OLS(endog = y, exog = x_sig).fit()
obj_OLS.summary()
x_sig_train, x_sig_test, y_sig_train, y_sig_test = train_test_split(x_sig, y, test_size=0.2,random_state=0)
mlrObj_sig = LinearRegression()
mlrObj_sig.fit(x_sig_train, y_sig_train)
y_sig_pred = mlrObj_sig.predict(x_sig_test)


In [33]:
y_test

array([ 37731, 122391,  57081,  63218, 116969, 109431], dtype=int64)

In [34]:
y_pred

array([ 43891.26902659, 126961.49881403,  62010.5455212 ,  61270.23196485,
       112780.99305321, 106171.56595799])

In [35]:
y_sig_pred

array([73886.20833333, 73886.20833333, 73886.20833333, 73886.20833333,
       73886.20833333, 73886.20833333])